### ISSUE TITLE
Document how encrypted message is sent back to Bob

### ISSUE THREAD

**Issue by petrdvorak** [wultra/sike-java#34]
Currently, we assume that the encrypted message somehow materializes on Bob's side but maybe we should be more specific about what is actually sent back to Bob. This may lead to providing `getEncoded()` method (or a similar one) on the `EncryptedMessage` class.

**Comment by romanstrobl** [comment]
Good point, yes, I think we should provided methods to serialize and deserialize the data for user convenience.
